# C?p nh?t c?u hình n?u c?n
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SportShopDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA c?u hình
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Upload file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB